"""changes

Revision ID: d02a442495c3
Revises: 
Create Date: 2023-07-13 20:17:57.991385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02a442495c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('main_unit_no', sa.String(), nullable=True),
    sa.Column('property_name', sa.String(), nullable=True),
    sa.Column('general_contact', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('lease_start_date', sa.Date(), nullable=True),
    sa.Column('lease_end_date', sa.Date(), nullable=True),
    sa.Column('vacate_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('transaction', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('exclusive', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('inclusive', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_transactions')
    op.drop_table('tenants')
    # ### end Alembic commands ###
